package router

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime"
	"strings"
	"syscall"
	"text/template"

	"github.com/kardianos/service"

	"github.com/Control-D-Inc/ctrld/internal/router/nvram"
)

const (
	merlinJFFSScriptPath             = "/jffs/scripts/services-start"
	merlinJFFSServiceEventScriptPath = "/jffs/scripts/service-event"
	merlinSvcScriptMarker             = "# GENERATED BY ctrld - Merlin service v2"
)

type merlinSvc struct {
	i        service.Interface
	platform string
	*service.Config
}

func newMerlinService(i service.Interface, platform string, c *service.Config) (service.Service, error) {
	s := &merlinSvc{
		i:        i,
		platform: platform,
		Config:   c,
	}
	return s, nil
}

func (s *merlinSvc) String() string {
	if len(s.DisplayName) > 0 {
		return s.DisplayName
	}
	return s.Name
}

func (s *merlinSvc) Platform() string {
	return s.platform
}

func (s *merlinSvc) configPath() string {
	bin := s.Config.Executable
	if bin == "" {
		path, err := os.Executable()
		if err != nil {
			return ""
		}
		bin = path
	}
	return bin + ".startup"
}

func (s *merlinSvc) template() *template.Template {
	return template.Must(template.New("").Funcs(template.FuncMap{
		"shellQuote": merlinShellQuote,
	}).Parse(merlinSvcScript))
}

func (s *merlinSvc) legacyTemplate() *template.Template {
	return template.Must(template.New("").Parse(merlinLegacySvcScript))
}

func (s *merlinSvc) renderStartupScripts(exePath string) (current, legacy []byte, err error) {
	data := &struct {
		*service.Config
		Path string
	}{
		s.Config,
		exePath,
	}

	var currentBuf bytes.Buffer
	if err := s.template().Execute(&currentBuf, data); err != nil {
		return nil, nil, fmt.Errorf("render current Merlin startup script: %w", err)
	}
	var legacyBuf bytes.Buffer
	if err := s.legacyTemplate().Execute(&legacyBuf, data); err != nil {
		return nil, nil, fmt.Errorf("render legacy Merlin startup script: %w", err)
	}
	return currentBuf.Bytes(), legacyBuf.Bytes(), nil
}

// RefreshMerlinStartupScriptFromRunningBinary migrates an exact ctrld-owned
// legacy startup script from code executed by the newly launched binary.
//
// This is intentionally separate from merlinSvc.Start: during self-upgrade the
// process that calls Service.Start is still the old binary even after the
// executable on disk has been replaced. The new `ctrld run` process is the
// first reliable place where new lifecycle code is guaranteed to execute.
//
// Missing service state and user-custom startup scripts are harmless no-ops.
// Transient migration errors are returned to the caller, which should log and
// continue starting ctrld so the next daemon start can retry safely.
func RefreshMerlinStartupScriptFromRunningBinary() error {
	exePath, err := os.Executable()
	if err != nil {
		return err
	}
	return refreshMerlinStartupScriptForExecutable(exePath)
}

func refreshMerlinStartupScriptForExecutable(exePath string) error {
	s := &merlinSvc{
		Config: &service.Config{
			Name:       "ctrld",
			Executable: exePath,
		},
	}

	return withMerlinServiceLock(func() error {
		err := s.refreshMerlinStartupScript()
		if errors.Is(err, service.ErrNotInstalled) {
			return nil
		}
		return err
	})
}

type merlinStartupMigrationError struct {
	err    error
	legacy []byte
}

func (e *merlinStartupMigrationError) Error() string { return e.err.Error() }
func (e *merlinStartupMigrationError) Unwrap() error { return e.err }

func (s *merlinSvc) refreshMerlinStartupScript() error {
	exePath := s.Config.Executable
	if exePath == "" {
		var err error
		exePath, err = os.Executable()
		if err != nil {
			return err
		}
	}

	installed, exists, err := readExistingMerlinStartupScript(s.configPath())
	if err != nil {
		return err
	}
	if !exists {
		return service.ErrNotInstalled
	}

	// Current ctrld-owned scripts carry an explicit marker. Start/restart paths
	// are often constructed from svcConfig without the original install
	// Arguments, so never re-render a current script from that incomplete
	// lifecycle config.
	if merlinStartupScriptHasMarker(installed) {
		return nil
	}

	// v1.5.x scripts predate the marker. Recover the exact argv encoded in the
	// legacy cmd= line, then render both templates with those installed
	// arguments. Exact legacy byte equality is still required before migration;
	// anything else is treated as user-owned/custom and left untouched.
	recovered, ok := recoverLegacyMerlinServiceConfig(installed, s.Config, exePath)
	if !ok {
		return nil
	}
	clone := *s
	clone.Config = recovered
	current, legacy, err := clone.renderStartupScripts(exePath)
	if err != nil {
		return err
	}
	if !bytes.Equal(installed, legacy) {
		return nil
	}
	exists, err = prepareExistingMerlinStartupScript(s.configPath(), current, legacy)
	if err != nil {
		return &merlinStartupMigrationError{
			err:    err,
			legacy: append([]byte(nil), legacy...),
		}
	}
	if !exists {
		return service.ErrNotInstalled
	}
	return nil
}

func merlinStartupScriptHasMarker(buf []byte) bool {
	for _, line := range strings.Split(string(buf), "\n") {
		if strings.TrimSuffix(line, "\r") == merlinSvcScriptMarker {
			return true
		}
	}
	return false
}

func recoverLegacyMerlinServiceConfig(buf []byte, base *service.Config, exePath string) (*service.Config, bool) {
	var cmdLine string
	for _, line := range strings.Split(string(buf), "\n") {
		if strings.HasPrefix(line, `cmd="`) && strings.HasSuffix(line, `"`) {
			cmdLine = strings.TrimSuffix(strings.TrimPrefix(line, `cmd="`), `"`)
			break
		}
	}
	if cmdLine == "" {
		return nil, false
	}
	fields := strings.Fields(cmdLine)
	if len(fields) == 0 || fields[0] != exePath {
		return nil, false
	}
	cfg := *base
	cfg.Executable = exePath
	cfg.Arguments = append([]string(nil), fields[1:]...)
	return &cfg, true
}

func merlinShellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

func merlinStartupHookLines(configPath string) (startLine, serviceEventLine string) {
	path := merlinShellQuote(configPath)
	return path + " start", path + ` service_event "$1" "$2"`
}

func merlinLegacyStartupHookLines(configPath string) (startLine, serviceEventLine string) {
	return configPath + " start", configPath + ` service_event "$1" "$2"`
}

func writeMerlinStartupScript(path string, data []byte, mode os.FileMode) (published bool, retErr error) {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".ctrld-*")
	if err != nil {
		return false, err
	}
	tmpPath := tmp.Name()
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
	}()

	if err := tmp.Chmod(mode); err != nil {
		return false, err
	}
	if _, err := tmp.Write(data); err != nil {
		return false, err
	}
	if err := tmp.Sync(); err != nil {
		return false, err
	}
	if err := tmp.Close(); err != nil {
		return false, err
	}

	// Publish without replacement semantics. If another actor creates the
	// startup script after our preflight, leave that file untouched.
	if err := os.Link(tmpPath, path); err != nil {
		return false, err
	}
	published = true

	if err := os.Remove(tmpPath); err != nil {
		return true, err
	}
	if err := syncMerlinServiceDir(dir); err != nil {
		return true, err
	}
	return true, nil
}

func syncMerlinServiceDir(dir string) error {
	// Merlin runs on Unix/Linux where fsyncing the parent directory is the
	// durability barrier for link/unlink publication. Windows does not permit
	// syncing directory handles; skip this Unix-specific barrier there so the
	// cross-platform package tests exercise the publication logic correctly.
	if runtime.GOOS == "windows" {
		return nil
	}
	f, err := os.Open(dir)
	if err != nil {
		return err
	}
	defer f.Close()
	return f.Sync()
}

func createMerlinSharedHookStub(path string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".ctrld-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
	}()

	// Build the complete executable stub privately first. Publishing only after
	// chmod/write/fsync succeed means a short write or ENOSPC can never leave a
	// partial shared hook at the public path.
	if err := tmp.Chmod(0755); err != nil {
		return err
	}
	if _, err := tmp.Write([]byte("#!/bin/sh\n")); err != nil {
		return err
	}
	if err := tmp.Sync(); err != nil {
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	// Publish with no-clobber semantics. If another addon creates or replaces
	// the hook while we are preparing the stub, Link returns EEXIST and the
	// caller revalidates that actor's file instead of truncating or deleting it.
	if err := os.Link(tmpPath, path); err != nil {
		return err
	}
	if err := os.Remove(tmpPath); err != nil {
		return err
	}
	if err := syncMerlinServiceDir(dir); err != nil {
		// The public stub may already be durable. Keep it in place so a retry can
		// revalidate/reuse it; never roll back a shared pathname after publish.
		return err
	}
	return nil
}
func validateMerlinSharedHookPath(path string, requireExecutable bool) (exists bool, err error) {
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	// sed -i may replace a symlink rather than edit its target. Shared Merlin
	// hooks must therefore be real regular files before ctrld edits them.
	if !info.Mode().IsRegular() {
		return true, fmt.Errorf("shared Merlin hook is not a regular file: %s", path)
	}
	if requireExecutable && info.Mode().Perm()&0111 == 0 {
		return true, fmt.Errorf("shared Merlin hook is not executable: %s", path)
	}
	return true, nil
}

func (s *merlinSvc) Install() error {
	return withMerlinServiceLock(s.installLocked)
}

func (s *merlinSvc) installLocked() error {
	exePath, err := os.Executable()
	if err != nil {
		return err
	}

	if !strings.HasPrefix(exePath, "/jffs/") {
		return errors.New("could not install service outside /jffs")
	}
	if _, err := nvram.Run("set", "jffs2_scripts=1"); err != nil {
		return err
	}
	if _, err := nvram.Run("commit"); err != nil {
		return err
	}

	confPath := s.configPath()

	// Render both current and last-known legacy templates before touching the
	// destination. An exact legacy match can be migrated safely during install
	// or upgrade; any other differing file is treated as user-owned.
	currentStartup, legacyStartup, err := s.renderStartupScripts(exePath)
	if err != nil {
		return err
	}
	startupExists, err := prepareExistingMerlinStartupScript(confPath, currentStartup, legacyStartup)
	if err != nil {
		return fmt.Errorf("prepare existing startup script: %w", err)
	}
	if !startupExists {
		if _, err := writeMerlinStartupScript(confPath, currentStartup, 0755); err != nil {
			// A successfully linked private startup script is intentionally kept
			// even if a later durability/hook step fails. It does not register the
			// service by itself, is safe to recognize on retry, and avoiding
			// pathname-based rollback prevents deleting an external replacement.
			return fmt.Errorf("publish startup script: %w", err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(merlinJFFSScriptPath), 0755); err != nil {
		return fmt.Errorf("os.MkdirAll: %w", err)
	}

	tmpScript, err := os.CreateTemp("", "ctrld_install")
	if err != nil {
		return fmt.Errorf("os.CreateTemp: %w", err)
	}
	defer os.Remove(tmpScript.Name())
	defer tmpScript.Close()

	if _, err := tmpScript.WriteString(merlinAddLineToScript); err != nil {
		return fmt.Errorf("tmpScript.WriteString: %w", err)
	}
	if err := tmpScript.Close(); err != nil {
		return fmt.Errorf("tmpScript.Close: %w", err)
	}
	cleanupCreatedHook := func(line, script string) {
		// Remove only ctrld's exact managed line first. If the file is still the
		// pristine stub ctrld created, remove it; otherwise preserve any content
		// another addon/user added concurrently.
		_ = exec.Command("sh", tmpScript.Name(), line, script, "remove").Run()
		buf, err := os.ReadFile(script)
		if err == nil && bytes.Equal(buf, []byte("#!/bin/sh\n")) {
			_ = os.Remove(script)
		}
	}

	addLineToScript := func(line, script string) (created, added bool, retErr error) {
		for {
			exists, err := validateMerlinSharedHookPath(script, true)
			if err != nil {
				return false, false, err
			}
			if exists {
				break
			}

			// Create a missing shared hook without following a raced symlink or
			// truncating a file another addon created after our Lstat.
			if err := createMerlinSharedHookStub(script); err != nil {
				if os.IsExist(err) {
					// Another actor won the race. Re-run Lstat validation against
					// the now-existing path before deciding whether it is safe.
					continue
				}
				return false, false, err
			}
			created = true
			break
		}
		defer func() {
			if retErr != nil && created {
				// On an editor failure ownership of any non-stub content is
				// ambiguous. Remove only the untouched stub; otherwise leave the
				// file for a safe resumable retry.
				buf, err := os.ReadFile(script)
				if err == nil && bytes.Equal(buf, []byte("#!/bin/sh\n")) {
					_ = os.Remove(script)
				}
			}
		}()

		// A pre-existing shared hook owns its mode. Do not chmod it as a side
		// effect of installing ctrld. The editor reports whether this invocation
		// actually appended the line so rollback never removes a pre-existing
		// ctrld hook line.
		out, err := exec.Command("sh", tmpScript.Name(), line, script, "add").CombinedOutput()
		if err != nil {
			return created, false, fmt.Errorf("exec.Command: add startup script: %s: %w", strings.TrimSpace(string(out)), err)
		}
		switch strings.TrimSpace(string(out)) {
		case "":
			return created, false, nil
		case "added":
			return created, true, nil
		default:
			return created, false, fmt.Errorf("unexpected hook editor output: %q", strings.TrimSpace(string(out)))
		}
	}

	type hookLine struct {
		script  string
		line    string
		created bool
		added   bool
	}
	startLine, serviceEventLine := merlinStartupHookLines(s.configPath())
	hooks := []hookLine{
		{script: merlinJFFSScriptPath, line: startLine},
		{script: merlinJFFSServiceEventScriptPath, line: serviceEventLine},
	}
	installed := make([]hookLine, 0, len(hooks))
	for _, hook := range hooks {
		created, added, err := addLineToScript(hook.line, hook.script)
		if err != nil {
			// Best-effort rollback: remove only lines successfully installed by
			// this attempt. Shared hook files created by ctrld are removed again;
			// pre-existing hooks keep all unrelated content.
			for i := len(installed) - 1; i >= 0; i-- {
				prev := installed[i]
				if prev.created {
					if prev.added {
						cleanupCreatedHook(prev.line, prev.script)
					}
					continue
				}
				if prev.added {
					_ = exec.Command("sh", tmpScript.Name(), prev.line, prev.script, "remove").Run()
				}
			}
			return err
		}
		hook.created = created
		hook.added = added
		installed = append(installed, hook)
	}

	return nil
}

func (s *merlinSvc) Uninstall() error {
	return withMerlinServiceLock(s.uninstallLocked)
}

func (s *merlinSvc) uninstallLocked() error {
	tmpScript, err := os.CreateTemp("", "ctrld_uninstall")
	if err != nil {
		return fmt.Errorf("os.CreateTemp: %w", err)
	}
	defer os.Remove(tmpScript.Name())
	defer tmpScript.Close()

	if _, err := tmpScript.WriteString(merlinRemoveLineFromScript); err != nil {
		return fmt.Errorf("tmpScript.WriteString: %w", err)
	}
	if err := tmpScript.Close(); err != nil {
		return fmt.Errorf("tmpScript.Close: %w", err)
	}
	removeLineFromScript := func(line, script string) error {
		exists, err := validateMerlinSharedHookPath(script, false)
		if err != nil {
			return err
		}
		if !exists {
			// Shared Merlin hooks belong to the router/user. Uninstalling ctrld
			// must not create a hook file that did not exist.
			return nil
		}

		if err := exec.Command("sh", tmpScript.Name(), line, script, "remove").Run(); err != nil {
			return fmt.Errorf("exec.Command: remove startup script: %w", err)
		}
		return nil
	}

	startLine, serviceEventLine := merlinStartupHookLines(s.configPath())
	legacyStartLine, legacyServiceEventLine := merlinLegacyStartupHookLines(s.configPath())
	for _, hook := range []struct {
		script string
		lines  []string
	}{
		{merlinJFFSScriptPath, []string{startLine, legacyStartLine}},
		{merlinJFFSServiceEventScriptPath, []string{serviceEventLine, legacyServiceEventLine}},
	} {
		for _, line := range hook.lines {
			if err := removeLineFromScript(line, hook.script); err != nil {
				return err
			}
		}
	}

	// Remove ctrld's private startup script only after all shared hook
	// references have been removed successfully.
	if err := os.Remove(s.configPath()); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("os.Remove: %w", err)
	}
	return nil
}

func (s *merlinSvc) Logger(errs chan<- error) (service.Logger, error) {
	if service.Interactive() {
		return service.ConsoleLogger, nil
	}
	return s.SystemLogger(errs)
}

func (s *merlinSvc) SystemLogger(errs chan<- error) (service.Logger, error) {
	return newSysLogger(s.Name, errs)
}

func (s *merlinSvc) Run() (err error) {
	err = s.i.Start(s)
	if err != nil {
		return err
	}

	if interactice, _ := isInteractive(); !interactice {
		signal.Ignore(syscall.SIGHUP)
	}

	var sigChan = make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGTERM, os.Interrupt)
	<-sigChan

	return s.i.Stop(s)
}

func (s *merlinSvc) Status() (service.Status, error) {
	if _, err := os.Stat(s.configPath()); os.IsNotExist(err) {
		return service.StatusUnknown, service.ErrNotInstalled
	} else if err != nil {
		return service.StatusUnknown, err
	}
	out, err := exec.Command(s.configPath(), "status").CombinedOutput()
	return merlinServiceStatus(out, err)
}

func merlinServiceStatus(out []byte, cmdErr error) (service.Status, error) {
	switch string(bytes.TrimSpace(out)) {
	case "running":
		if cmdErr != nil {
			return service.StatusUnknown, cmdErr
		}
		return service.StatusRunning, nil
	case "stopped":
		// The generated BusyBox script intentionally exits 1 for "stopped".
		// That is a state, not a failure to determine the state.
		return service.StatusStopped, nil
	default:
		if cmdErr != nil {
			return service.StatusUnknown, cmdErr
		}
		return service.StatusUnknown, fmt.Errorf("unexpected Merlin service status output: %q", bytes.TrimSpace(out))
	}
}

func (s *merlinSvc) Start() error {
	return withMerlinServiceLock(s.startLocked)
}

func (s *merlinSvc) startLocked() error {
	// Upgrades replace only the binary before restarting the service. Refresh
	// an exact ctrld-owned legacy startup script here as a secondary path; the
	// newly launched binary also performs this migration from ctrld run.
	if err := s.refreshMerlinStartupScript(); err != nil {
		var migrationErr *merlinStartupMigrationError
		if !errors.As(err, &migrationErr) {
			return err
		}

		// Migration can fail before publication because JFFS is full/read-only or
		// reports an I/O error. The exact legacy script is intentionally left
		// intact in that case. Re-read it before fallback; if it is still the
		// recognized legacy bytes (or the migration actually published the
		// current marked script before a durability error), start it rather than
		// leaving DNS down. Anything else remains a hard error.
		canStart, readErr := canStartMerlinStartupAfterMigrationError(s.configPath(), migrationErr.legacy)
		if readErr != nil {
			return errors.Join(err, readErr)
		}
		if !canStart {
			return err
		}
	}
	return exec.Command(s.configPath(), "start").Run()
}

func canStartMerlinStartupAfterMigrationError(path string, legacy []byte) (bool, error) {
	installed, exists, err := readExistingMerlinStartupScript(path)
	if err != nil {
		return false, err
	}
	if !exists {
		return false, nil
	}
	return bytes.Equal(installed, legacy) || merlinStartupScriptHasMarker(installed), nil
}

func (s *merlinSvc) Stop() error {
	return withMerlinServiceLock(s.stopLocked)
}

func (s *merlinSvc) stopLocked() error {
	return exec.Command(s.configPath(), "stop").Run()
}

func (s *merlinSvc) Restart() error {
	return s.RestartWith(nil)
}

// RestartWith serializes the complete Merlin stop/between/start transaction.
// The callback lets the CLI keep router cleanup, DNS restoration and process
// wait semantics inside the same cross-process lifecycle lock.
func (s *merlinSvc) RestartWith(between func() error) error {
	return withMerlinServiceLock(func() error {
		if err := s.stopLocked(); err != nil {
			return err
		}
		if between != nil {
			if err := between(); err != nil {
				return err
			}
		}
		return s.startLocked()
	})
}

const merlinLegacySvcScript = `#!/bin/sh

name="{{.Name}}"
cmd="{{.Path}}{{range .Arguments}} {{.}}{{end}}"
pid_file="/tmp/$name.pid"

get_pid() {
  cat "$pid_file"
}

is_running() {
  [ -f "$pid_file" ] && ps | grep -q "^ *$(get_pid) "
}

case "$1" in
  start)
    if is_running; then
      logger -c "Already started"
    else
      logger -c "Starting $name"
      if [ -f /rom/ca-bundle.crt ]; then
        # For John’s fork
        export SSL_CERT_FILE=/rom/ca-bundle.crt
      fi
      $cmd &
      echo $! > "$pid_file"
      chmod 600 "$pid_file"
      if ! is_running; then
       logger -c "Failed to start $name"
       exit 1
      fi
    fi
  ;;
  stop)
    if is_running; then
      logger -c "Stopping $name..."
      kill "$(get_pid)"
      for _ in 1 2 3 4 5; do
        if ! is_running; then
          logger -c "stopped"
          if [ -f "$pid_file" ]; then
            rm "$pid_file"
          fi
          exit 0
        fi
        printf "."
        sleep 2
      done
      logger -c "failed to stop $name"
      exit 1
    fi
    exit 0
  ;;
  restart)
    $0 stop
    $0 start
  ;;
  status)
    if is_running; then
      echo "running"
    else
      echo "stopped"
      exit 1
    fi
  ;;
  service_event)
    event=$2
    svc=$3
    dnsmasq_pid_file=$(sed -n '/pid-file=/s///p' /etc/dnsmasq.conf)

    if [ "$event" = "restart" ] && [ "$svc" = "diskmon" ]; then
      kill "$(cat "$dnsmasq_pid_file")" >/dev/null 2>&1
    fi
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
  ;;
esac
exit 0
`

const merlinSvcScript = `#!/bin/sh
# GENERATED BY ctrld - Merlin service v2

name={{shellQuote .Name}}
exe={{shellQuote .Path}}
pid_file="/tmp/$name.pid"

get_pid() {
  [ -r "$pid_file" ] || return 1
  pid="$(cat "$pid_file" 2>/dev/null)" || return 1
  case "$pid" in
    ''|*[!0-9]*) return 1 ;;
  esac
  printf '%s\n' "$pid"
}

is_running_pid() {
  pid=$1
  [ -n "$pid" ] || return 1
  [ -r "/proc/$pid/cmdline" ] || return 1
  process_cmd="$(tr '\000' ' ' < "/proc/$pid/cmdline" 2>/dev/null)" || return 1
  case "$process_cmd" in
    "$exe"|"$exe "*) return 0 ;;
    *) return 1 ;;
  esac
}

is_running() {
  pid="$(get_pid)" || return 1
  is_running_pid "$pid"
}
case "$1" in
  start)
    if is_running; then
      logger -c "Already started"
    else
      rm -f "$pid_file"
      logger -c "Starting $name"
      if [ -f /rom/ca-bundle.crt ]; then
        # For John’s fork
        export SSL_CERT_FILE=/rom/ca-bundle.crt
      fi
      {{shellQuote .Path}}{{range .Arguments}} {{shellQuote .}}{{end}} &
      echo $! > "$pid_file"
      chmod 600 "$pid_file"
      started=0
      for _ in 1 2 3 4 5; do
        if is_running; then
          started=1
          break
        fi
        sleep 1
      done
      if [ "$started" -ne 1 ]; then
        logger -c "Failed to start $name"
        rm -f "$pid_file"
        exit 1
      fi
    fi
  ;;
  stop)
    pid="$(get_pid)" || {
      rm -f "$pid_file"
      exit 0
    }
    if is_running_pid "$pid"; then
      logger -c "Stopping $name..."
      kill "$pid"
      for _ in 1 2 3 4 5; do
        if ! is_running_pid "$pid"; then
          logger -c "stopped"
          if [ -f "$pid_file" ]; then
            rm "$pid_file"
          fi
          exit 0
        fi
        printf "."
        sleep 2
      done
      logger -c "failed to stop $name"
      exit 1
    fi
    rm -f "$pid_file"
    exit 0
  ;;
  restart)
    "$0" stop || exit $?
    "$0" start
  ;;
  status)
    if is_running; then
      echo "running"
    else
      echo "stopped"
      exit 1
    fi
  ;;
  service_event)
    event=$2
    svc=$3
    dnsmasq_pid_file=$(sed -n '/pid-file=/s///p' /etc/dnsmasq.conf)

    if [ "$event" = "restart" ] && [ "$svc" = "diskmon" ] && [ -r "$dnsmasq_pid_file" ]; then
      dnsmasq_pid="$(cat "$dnsmasq_pid_file" 2>/dev/null)"
      case "$dnsmasq_pid" in
        ''|*[!0-9]*) dnsmasq_pid="" ;;
      esac
      if [ -n "$dnsmasq_pid" ] && [ -r "/proc/$dnsmasq_pid/cmdline" ]; then
        dnsmasq_exe="$(tr '\000' '\n' < "/proc/$dnsmasq_pid/cmdline" 2>/dev/null | sed -n '1p')"
        case "$dnsmasq_exe" in
          dnsmasq|*/dnsmasq) kill "$dnsmasq_pid" >/dev/null 2>&1 ;;
        esac
      fi
    fi
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
  ;;
esac
exit 0
`

const merlinAddLineToScript = `#!/bin/sh

line=$1
file=$2
mode=$3

. /usr/sbin/helper.sh

if [ "$mode" = "remove" ]; then
  pattern=$(_quote "$line")
  sed -i "/^$pattern$/d" "$file"
else
  if grep -qxF "$line" "$file"; then
    exit 0
  else
    grep_status=$?
    [ "$grep_status" -eq 1 ] || exit "$grep_status"
  fi
  pc_append "$line" "$file" || exit $?
  printf 'added\n'
fi
`

const merlinRemoveLineFromScript = `#!/bin/sh

line=$1
file=$2

. /usr/sbin/helper.sh

pattern=$(_quote "$line")
sed -i "/^$pattern$/d" "$file"
`
